// Authentic Rishihood University Mess Menu
const messMenu = {
  Monday: {
    breakfast: [
      'Banana',
      'SEMIYA Upma',
      'MUJHAL Idli',
      'Sambar and Coconut Chutney',
      'Hot Milk',
      'Cold Milk',
      'Tea',
      'Coffee Powder',
      'Bread',
      'Butter',
      'Jam',
    ],
    lunch: ['Mixed Rusk', 'Green Salad', 'Chole Masala', 'Masale da Baingan'],
    snacks: ['Bread', 'Pakoda', 'Chutney', 'Cold Coffee', 'Tea'],
    dinner: ['Toasted Salad', 'Rajma Masala', 'Aloo Mutter Fry', 'Dry PULUSU Rice', 'Chapati'],
    times: {
      breakfast: '7:30 AM – 9:30 AM',
      lunch: '12:30 PM – 2:30 PM',
      snacks: '2:30 PM – 6:30 PM',
      dinner: '7:30 PM – 9:30 PM',
    },
  },
  Tuesday: {
    breakfast: [
      'Mixed Fruits',
      'Boiled Churra / Chana',
      'Chocos',
      'Plain Paratha',
      'Bhaji',
      'Hot Milk',
      'Cold Milk',
      'Tea',
      'Coffee Powder',
      'Bread',
      'Butter',
      'Jam',
    ],
    lunch: [
      'Veg Biryani',
      'Jeera Raita',
      'Mint Lachha Onion',
      'Mirch Ka Salan',
      'Karam Chutney',
      'Dhaba Dal',
      'Chapati',
      'Gulab Jamun',
    ],
    snacks: ['Aloo Matar Puff', 'Ketchup', 'Hot Milk', 'Tea', 'Cold Coffee'],
    dinner: [
      'Green Salad',
      'Soya Chaap Masala',
      'Moong-Masoor Dal',
      'Gokarkai Kura',
      'Jeera Rice',
      'Chapati',
      'Gulab Jamun',
    ],
    times: {
      breakfast: '7:30 AM – 9:30 AM',
      lunch: '12:30 PM – 2:30 PM',
      snacks: '4:30 PM – 6:30 PM',
      dinner: '7:30 PM – 9:30 PM',
    },
  },
  Wednesday: {
    breakfast: [
      'Papaya',
      'Masala Oats',
      'Cornflakes',
      'Pav',
      'Missal',
      'Hot Milk (D)',
      'Cold Milk (D)',
      'Tea (D)',
      'Coffee Powder',
      'Bread/Butter/Jam',
    ],
    lunch: [
      'Chach',
      'Green Salad',
      'Paneer Butter Masala',
      'Mix Yellow Dal',
      'Plain Rice',
      'Chapati',
      'Ice Cream',
    ],
    snacks: ['Jhal Muri', 'Cold Coffee', 'Tea (D)'],
    dinner: [
      'Onion Lachha',
      'Parwal Aloo Dry',
      'Arhar Dal Tarka',
      'Bendakai Kura',
      'Plain Rice',
      'Chapati',
    ],
  },
  Thursday: {
    breakfast: [
      'Water Melon',
      'Moong Sprout',
      'Muesli',
      'Ajwain Poori',
      'Aloo Matar Sabji',
      'Hot Milk (D)',
      'Cold Milk (D)',
      'Tea (D)',
      'Coffee Powder',
      'Bread/Butter/Jam',
    ],
    lunch: [
      'Aam Panna',
      'Green Salad',
      'Kadhi Pakora',
      'Aloo Matar Capsicum',
      'Sambar',
      'Dhania Rice',
      'Chapati',
      'No desert',
    ],
    snacks: ['Samosa', 'Ketchup', 'Hot Milk (D)', 'Tea (D)', 'Coffee Powder'],
    dinner: [
      'Cucumber Salad',
      'Tofu Manchurian',
      'Chole Punjabi',
      'Yonkai Kura',
      'Peas Rice',
      'Chapati',
      'Rice Kheer',
    ],
  },
  Friday: {
    breakfast: [
      'Banana',
      'Chocos',
      'Macaroni',
      'Besan Chilla',
      'Hara Chutney',
      'Hot Milk (D)',
      'Cold Milk (D)',
      'Tea (D)',
      'Coffee Powder',
      'Bread/Butter/Jam',
    ],
    lunch: [
      'Rooh-Afza',
      'Tossed Salad',
      'Cabbage Matar Tamatar',
      'Rajmah',
      'Beans Coconut',
      'Plain Rice',
      'Chapati',
      'Pastry',
    ],
    snacks: ['French Fries', 'Ketchup', 'Cold Coffee', 'Tea (D)', 'Coffee Powder'],
    dinner: ['Green Salad', 'Paneer Makhni', 'Yellow Moong Dal', 'Sambar', 'Jeera Rice', 'Chapati'],
  },
  Saturday: {
    breakfast: [
      'Mix Fruits',
      'Cornflakes',
      'Sandwich',
      'Veg Uttapam',
      'Sambar & Chutney',
      'Hot Milk (D)',
      'Cold Milk (D)',
      'Tea (D)',
      'Coffee Powder',
      'Bread/Butter/Jam',
    ],
    lunch: [
      'Salted Lassi',
      'Cucumber-Carrot Salad',
      'Lauki Kofta Curry',
      'Arhar Dal Tarka',
      'Dondakai',
      'Ghee Rice',
      'Chapati',
    ],
    snacks: ['Maggi', 'Hot Milk (D)', 'Tea (D)', 'Coffee Powder'],
    dinner: [
      'Moong Sprout Salad',
      'Kundru Aloo Chatpata',
      'Gota Masoor',
      'Beans Podi',
      'Ghee Rice',
      'Chapati',
      'Choco Moose',
    ],
  },
  Sunday: {
    breakfast: [
      'Papaya',
      'Muesli',
      'Dalia',
      'Paneer - Pyaaz Aloo Paratha',
      'Curd & Pickle',
      'Cold/Hot Milk (D)',
      'Tea (D)',
      'Coffee Powder',
      'Bread/Butter/Jam',
    ],
    lunch: [
      'Butter Milk',
      'Lachha Onion',
      'Dal Makhni',
      'Mix Veg Bhaji',
      'Sambar',
      'Plain Rice',
      'Poori',
      'Besan Ladoo',
    ],
    snacks: ['Burger', 'Ketchup', 'Cold Coffee', 'Tea (D)', 'Coffee Powder'],
    dinner: ['Cucumber Salad', 'Dhaba Dal', 'Makhana Matar', 'Rasam', 'Steamed Rice', 'Chapati'],
  },
};

const mealTimes12h = {
  breakfast: { time12h: '8:00 AM', startHour: 7, endHour: 10, label: 'Breakfast' },
  lunch: { time12h: '1:00 PM', startHour: 12, endHour: 15, label: 'Lunch' },
  snacks: { time12h: '5:00 PM', startHour: 16, endHour: 18, label: 'Evening Snacks' },
  dinner: { time12h: '8:00 PM', startHour: 19, endHour: 22, label: 'Dinner' },
};

module.exports = { messMenu, mealTimes12h };
